#!/bin/bash
#get the data from the website

curl -s "https://aviationweather.gov/api/data/metar?ids=KMCI&format=json&taf=false&hours=12&bbox=40%2C-90%2C45%2C-85" > aviation.json
#loop through the first 6 lines and get the specified field
for i in {1..6}; do
cat ../lab8/aviation.json | jq .[$i].receiptTime
done
